name: Development

on:
   workflow_dispatch: 

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
        - name: Check out the source code
          uses: actions/checkout@v3
        - name: Count TODOs
          uses: ./